---
apiVersion: batch/v1
kind: Job
metadata:
  name: checkup-framework
  namespace: k8s-checkup-framework
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: checkup-framework-sa
      restartPolicy: Never
      containers:
      - name: checkup-framework
        resources:
        image: registry:5000/checkup-framework:latest
        env:
        - name: CONFIGMAP_NAMESPACE
          value: k8s-checkup-framework
        - name: CONFIGMAP_NAME
          value: kubevirt-vm-latency-checkup-example-config