#!/usr/bin/env bash

set -e

FRAMEWORK_ENV_MANIFEST_FILE="./manifests/k8s-checkup-framework.yaml"

kubectl version

echo
date +"%Y-%m-%dT%H:%M:%S%:z" | tr -d \n
echo " Deploying framework..."
kubectl apply -f $FRAMEWORK_ENV_MANIFEST_FILE

echo
date +"%Y-%m-%dT%H:%M:%S%:z" | tr -d \n
echo " *** Done ***"
