#!/usr/bin/env bash

set -e

readonly SCRIPT_PATH=$(dirname "$(realpath "$0")")
readonly PROJECT_PATH=$(realpath $SCRIPT_PATH/..)

FRAMEWORK_ENV_MANIFEST_FILE="${PROJECT_PATH}/manifests/k8s-checkup-framework.yaml"

kubectl version

echo
date +"%Y-%m-%dT%H:%M:%S%:z" | tr -d "\n"
echo " Deploying framework..."
kubectl apply -f $FRAMEWORK_ENV_MANIFEST_FILE

echo
date +"%Y-%m-%dT%H:%M:%S%:z" | tr -d "\n"
echo " *** Done ***"
